import {useContext} from 'react';
import { langContext } from '../context';

const postCard = () => {
    const {t} = useContext(langContext)
    return (
        <div className='shadow-lg bg-warning p-4'>
            <h2 >{t.title}</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas sequi praesentium dolor eos porro delectus voluptates incidunt corporis. Odio ea modi dicta incidunt? Quas sequi, deleniti autem quaerat laudantium fugit incidunt est magni impedit. Ratione dolore provident optio. Placeat porro, tempora nostrum quod fuga velit nisi earum iure beatae dicta ipsam ipsa rerum mollitia itaque reiciendis illo explicabo tempore non cumque! Inventore laboriosam quidem tenetur architecto illum quo nam facere! Sint magnam ea dicta delectus quis corrupti facilis minus, maiores neque nulla, a necessitatibus incidunt dolorum in veniam unde iste suscipit? Possimus accusamus veniam iusto sapiente quis nobis, natus ipsum, laudantium dolorum odit a. Adipisci minus, tenetur blanditiis accusantium magnam, dolor sit facere molestiae commodi ex ut possimus debitis et? Dolor, sunt accusamus nostrum nisi deserunt iusto debitis, ea laudantium facere itaque rerum commodi aspernatur atque sequi, repellendus sit vero doloremque. Quae nesciunt excepturi debitis, voluptates, cupiditate rem dolore voluptatum ad iusto repellat minima magnam tenetur, suscipit laborum sint veritatis labore. Quia odio esse a eos eaque, nesciunt assumenda minus at sit delectus aperiam quis similique error, voluptas accusamus consequuntur, ratione velit ea qui deserunt. Omnis cum nam delectus ipsam dolorum error nemo assumenda nisi! Quidem optio cupiditate quis id praesentium maxime magni officiis maiores fugiat dicta illo possimus, commodi ipsam repellendus sapiente veniam molestias amet sunt. Ipsa sint neque soluta, exercitationem non aperiam dolorem, ea accusamus omnis voluptatem magni in atque error.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ducimus exercitationem libero repudiandae, explicabo fugiat tempore tenetur nostrum ex aut quasi.</p>
            <h2 >{t.title}</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas sequi praesentium dolor eos porro delectus voluptates incidunt corporis. Odio ea modi dicta incidunt? Quas sequi, deleniti autem quaerat laudantium fugit incidunt est magni impedit. Ratione dolore provident optio. Placeat porro, tempora nostrum quod fuga velit nisi earum iure beatae dicta ipsam ipsa rerum mollitia itaque reiciendis illo explicabo tempore non cumque! Inventore laboriosam quidem tenetur architecto illum quo nam facere! Sint magnam ea dicta delectus quis corrupti facilis minus, maiores neque nulla, a necessitatibus incidunt dolorum in veniam unde iste suscipit? Possimus accusamus veniam iusto sapiente quis nobis, natus ipsum, laudantium dolorum odit a. Adipisci minus, tenetur blanditiis accusantium magnam, dolor sit facere molestiae commodi ex ut possimus debitis et? Dolor, sunt accusamus nostrum nisi deserunt iusto debitis, ea laudantium facere itaque rerum commodi aspernatur atque sequi, repellendus sit vero doloremque. Quae nesciunt excepturi debitis, voluptates, cupiditate rem dolore voluptatum ad iusto repellat minima magnam tenetur, suscipit laborum sint veritatis labore. Quia odio esse a eos eaque, nesciunt assumenda minus at sit delectus aperiam quis similique error, voluptas accusamus consequuntur, ratione velit ea qui deserunt. Omnis cum nam delectus ipsam dolorum error nemo assumenda nisi! Quidem optio cupiditate quis id praesentium maxime magni officiis maiores fugiat dicta illo possimus, commodi ipsam repellendus sapiente veniam molestias amet sunt. Ipsa sint neque soluta, exercitationem non aperiam dolorem, ea accusamus omnis voluptatem magni in atque error.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ducimus exercitationem libero repudiandae, explicabo fugiat tempore tenetur nostrum ex aut quasi.</p>
        </div>
    );
};

export default postCard;